In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [11]:
a = np.array([1,2,3,5])

In [15]:
a, type(a), a.shape, a.ndim

(array([1, 2, 3, 5]), numpy.ndarray, (4,), 1)

In [19]:
a = np.array((1,2,3,5))
a, type(a), a.shape, a.ndim

(array([1, 2, 3, 5]), numpy.ndarray, (4,), 1)

In [23]:
# 0 dimensional
a = np.array(2)
a, type(a), a.shape, a.ndim

(array(2), numpy.ndarray, (), 0)

In [27]:
# 2 dimensional
a = np.array([[1,2,3,4],[1,2,3,4]])
a, type(a), a.shape, a.ndim

(array([[1, 2, 3, 4],
        [1, 2, 3, 4]]),
 numpy.ndarray,
 (2, 4),
 2)

In [39]:
# 3 dimensional -> list/vector of 2d list/vector
a = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
a, type(a), a.shape, a.ndim, len(a.shape), len(a)
# len shape is the dimension of the vector

(array([[[1, 2, 3, 4],
         [1, 2, 3, 4]],
 
        [[1, 2, 3, 4],
         [1, 2, 3, 4]]]),
 numpy.ndarray,
 (2, 2, 4),
 3,
 3,
 2)

In [45]:
a = np.array(['0', '1'], dtype='f')
a, a.dtype

(array([0., 1.], dtype=float32), dtype('float32'))

In [47]:
b = a.astype('i') #converting to int

In [51]:
b.astype('U') #converting back to unicode string

array(['0', '1'], dtype='<U11')

In [53]:
-np.sort(-a) #descending order sort!

array([1., 0.], dtype=float32)

nan -> not a number and 
inf -> inf

In [62]:
np.nan == np.nan
a = np.nan
b = np.nan
a, b

False

In [64]:
a ==b, a>b, a<b

(array([ True,  True]), array([False, False]), array([False, False]))

In [68]:
a = np.inf
b = np.inf
a, b

(inf, inf)

In [70]:
a==b, a>b

(True, False)

In [78]:
None == None

True

In [90]:
a = np.array([[1,2,3],[4,5,6]], dtype='f')
a.shape

(2, 3)

In [96]:
a[0][1] = np.nan
a[0][2] = np.inf #must be a float dtype
a

array([[ 1., nan, inf],
       [ 4.,  5.,  6.]], dtype=float32)

In [100]:
np.isnan(a), np.isinf(a), 

(array([[False,  True, False],
        [False, False, False]]),
 array([[False, False,  True],
        [False, False, False]]))

In [102]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [126]:
a.mean(), np.mean(a) #mean means avg

(2.0, 2.0)

In [128]:
a = np.array([1,3])
a.var() #variance describes how far each number is from the mean(avg)

1.0

In [130]:
a.std() #standard deviation describes dispersion (szórás) from the mean

1.0

In [132]:
np.median(a) #middle number

2.0

In [144]:
a = np.array([[1,2,3,4],[1,2,3,4]])
a.ndim, a.shape

(2, (2, 4))

In [158]:
a.reshape(1,8) #when reshaping values it makes a certain number of rows and coloums given in the parameters

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [160]:
a.reshape(1,-1) #-1 means it can make as many coloumns as it wants with only one row

array([[1, 2, 3, 4, 1, 2, 3, 4]])

In [156]:
a.ravel() #converts a into a 1D array. returns a view, but will change the original array (e.g. a[0][1] = 1 will change the original array)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [162]:
a.flatten() #flatten returns a copy but works similarly to ravel

array([1, 2, 3, 4, 1, 2, 3, 4])

In [176]:
np.arange(2,6, dtype='float') #not arrange()!
#generates an array from the given inddex, until the given last index

array([2., 3., 4., 5.])

In [182]:
np.arange(2,6,2, dtype='float')
# the third parameter here specifies how much it should add to the next array number as it generates

array([2., 4.])

In [197]:
np.linspace(1,11, 5, dtype='int') #opposed to the last function, with linspace you can specify the length of the returning array 
#BUT cannot change the difference between the valiues

array([ 1,  3,  6,  8, 11])

In [203]:
np.zeros([2,5]) #2d array of zeros, 2 rows, 5 cols. similar function: np.ones()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [205]:
#np also has the same range() and random() functions as the standard python library

In [209]:
np.tile([1,2,3], 2) #first params array will be repeated 2 times (concatenates the same array to the end)

array([1, 2, 3, 1, 2, 3])

In [213]:
np.repeat([1,2,3], 2) # works similarly, except it directly repeats the values after one another instead of concatenating to the end

array([1, 1, 2, 2, 3, 3])

In [223]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [235]:
index = np.where(a>3) #iterates through the array and gives back where the conditions return true (returns the indexes)

In [231]:
a[index] #shows the actual values where it returned true

array([4, 4])

In [239]:
np.where(a>3, 0, a) #if the a>4, replace a with 0

array([[1, 2, 3, 0],
       [1, 2, 3, 0]])

In [246]:
a.argmax() #maximum argument

3

In [250]:
a.flatten()[3] #by flattening and indexing you get back the max value (alternatively you can use max())

4

In [264]:
import os
os.makedirs('data', exist_ok=True) # needed to make an array, since save() wont do it by itself
np.save('data/a.npy', a) #fileanem and what you want to store

In [270]:
np.savetxt('data/a.csv', a, delimiter=',') #you cannot save a 3d array in csv. the txt in the function name can be confusing

In [272]:
b = np.array([a,a])
b.ndim, b.shape

(3, (2, 2, 4))

In [274]:
np.save('data/b.npy', b)

In [276]:
aa = np.loadtxt('data/a.csv', delimiter=',')

In [280]:
np.load('data/a.npy') #reads the binary data

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [282]:
np.load('data/b.npy')

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [296]:
np.savez('data/a.npz', a ,b) #saves multiple arrays like this

In [298]:
d = np.load('data/a.npz')

In [300]:
d.files

['arr_0', 'arr_1']

In [302]:
d['arr_0']

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [313]:
a = np.array([1,2])
b = np.array([3,4])
np.concatenate([a,b]) #dimensions must match

array([1, 2, 3, 4])

In [322]:
np.concatenate([a,b], axis= 0) #chooses where it concatenates ?

array([1, 2, 3, 4])

In [332]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
np.concatenate([a,b], axis= 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [334]:
np.concatenate([a,b], axis= 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [336]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [338]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])